### ISSUE TITLE
Configure some teleports to work with a job (answered)

### ISSUE THREAD

**Issue by vcmanny** [Horst-ui/EasyMarkerTeleporter#2]
hey I know I can configure all the teleports with a job but is there a way I can configure certain teleports to work with a certain job.

**Comment by Horst-ui** [comment]
you need to make each teleport "station" seperately in the client.lua, for a way to do this in the config I can look on it later

**Comment by vcmanny** [comment]
@Horst-ui yea sure that'd be great. do you have discord?

**Comment by Horst-ui** [comment]
Horst#6525

**Comment by vcmanny** [comment]
Anyone else that wants to have some markers for everyone and some markers for a certain job: 

duplicate the entire file, change the name, and configure that one to the job you like.
